### ISSUE TITLE
Improve the PWA workshop

### ISSUE THREAD

**Issue by jlengstorf** [jlengstorf/presentations#1]
- [x] Write the manifest.json by hand before using the generator
- [x] Write the serviceworker.js by hand before using the generator

It's not important to be able to write these by hand every time, but it _is_ really important to understand what's happening under the hood.

**Comment by jlengstorf** [comment]
@hugogiraudel I implemented the feedback you gave me a few weeks back — the workshop went MUCH better. (Well, that and the fact I fixed all my npm issues on Windows.) :)

Thanks again!

**Comment by HugoGiraudel** [comment]
Yaaay! Excellent. Always glad to helpç
