### ISSUE TITLE
[Beyond Static] Request for online recording

### ISSUE THREAD

**Issue by AbhimanyuAryan** [jlengstorf/presentations#8]
I won't be there in GOA to attend this talk. Can you assure that organizers upload a high-quality video/audio output on youtube?

**Comment by jlengstorf** [comment]
I'm not sure I can guarantee anything, but if they provide a video I'll share it. A previous version of this talk is available here: https://www.youtube.com/watch?v=wNUg1jpj9T0&list=PLz8Iz-Fnk_eQGt4-VFFCXYuYcuKaw4F07&index=9
